### ISSUE TITLE
wiki_revision_trained_embedding.bin not found

### ISSUE THREAD

**Issue by FRYoussef** [diyiy/Wiki_Semantic_Intention#2]
Hello,
I´m trying to run your script but it crashes because the file "wiki_revision_trained_embedding.bin" is not found. Can you add it, please?

Thanks.

**Comment by diyiy** [comment]
Fixed. This is a trained word embedding. You can download it from https://drive.google.com/drive/u/0/folders/1i8gIJvqjt_pOcBZcWj1ZkRdHU90ZeTHw.
